---
- name: Java setup
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.java
      java_packages: 
        - openjdk-8-jdk

- name: Zookeeper cluster setup
  hosts: zookeeper
  become: yes
  roles:
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_hosts: "{{ groups['zookeeper'] }}"